
drop table account if exists;
create table account (
   id bigint generated by default as identity,
    created_at timestamp,
    updated_at timestamp,
    role varchar(255),
    user_name varchar(255),
    user_pw varchar(255),
    primary key (id)
)
drop table history_access_token if exists;
create table history_access_token (
   id bigint generated by default as identity,
    created_at timestamp,
    updated_at timestamp,
    access_token varchar(255),
    user_name varchar(255),
    primary key (id)
)
drop table history_refresh_token if exists;
create table history_refresh_token (
   id bigint generated by default as identity,
    created_at timestamp,
    updated_at timestamp,
    refresh_token varchar(255),
    user_name varchar(255),
    primary key (id)
)

drop table refresh_token if exists;
create table refresh_token (
   id bigint generated by default as identity,
    created_at timestamp,
    updated_at timestamp,
    access_token varchar(255),
    refresh_token varchar(255),
    user_name varchar(255),
    primary key (id)
)